name: vip
seed: 92

# Model
model:
  architecture: UnetPlusPlus
  encoder: timm-regnety_320
  encoder_weight: imagenet
  n_classes: 1
  in_channel: 3
  pretrained: False
  
# Dataset
data_dir: ./data/data_512
kfold: 2

# Data Loader
input_size: 224
num_workers: 8
val_size: 0.1
n_epochs: 400
batch_size: 64
ricap_size: 0

loss: 
  name: BCEWithLogitsLoss
  # name: DiceCELoss

optimizer:
  name: Adam
  args:
    lr: 1.0e-03
    # weight_decay: 0.1
    # momentum: 0.9

scheduler:
  name: CosineAnnealingLR
  args:
    T_max: 300
    eta_min: 0

amp: True