seed: 42

# Model
model:
  name: segformer
  weight: nvidia/segformer-b4-finetuned-ade-512-512

# Dataset
data_dir: ./data/data_1024_2
processor: nvidia/segformer-b4-finetuned-ade-512-512

# Data Loader
input_size: 224
num_workers: 8
val_size: 0.1
n_epochs: 400
batch_size: 64

# Loss
loss:
  name: BCEWithLogitsLoss

# Optimizer
optimizer:
  name: AdamW
  args:
    lr: 5.0e-04
    weight_decay: 2.0e-02

# Scheduler
scheduler:
  name: ExponentialLR
  args:
    gamma: 0.96

amp: True

step:
  isthatrue: False
  idx: 100
