seed: 42

# Model
model:
  name: segformer
  weight: nvidia/segformer-b4-finetuned-ade-512-512
  
# Dataset
data_dir: ./data/data_1024
processor: nvidia/segformer-b4-finetuned-ade-512-512

# Data Loader
input_size: 224
num_workers: 8
val_size: 0.1
n_epochs: 100
batch_size: 8

loss: 
  # name: BCEWithLogitsLoss
  name: DiceCELoss

optimizer:
  name: AdamW
  args:
    lr: 5.0e-04
    weight_decay: 5.0e-02

scheduler:
  name: CosineAnnealingLR
  args:
    T_max: 100
    eta_min: 0

amp: True

step: 
  isthatrue: False
  idx: 100